whatwg/wattsi

src/wattsi.pas
=> Remove <img src> rewriting and data-revision support

src/wattsi.pas
See https://github.com/whatwg/html-build/issues/33 for details.
=> Use path-absolute URLs to avoid file duplication

README.md
See related discussion at http://logs.glob.uno/?c=freenode%23whatwg&s=8%20Jan%202016&e=8%20Jan%202016#c979900
=> Retitle「Troubleshooting」for accuracy & tone down

src/wattsi.pas
=> Fix #14: Ignore caniuse links that point to w3.org

src/wattsi.pas
Part of https://github.com/whatwg/html/issues/2026
=> Don't modify link-fixup.js in wattsi

src/build.sh, src/wattsi.pas
Relates to https://github.com/whatwg/html-build/issues/84
=> Add --version option

src/wattsi.pas
=> Wrap heading section numbers in <span class=secno>

src/wattsi.pas
=> Make xrefs.json include cross-spec definitions

src/wattsi.pas
=> Add an "index" class to the multipage index.html

src/wattsi.pas
This makes Wattsi create the search-index.json file used by the dev edition.
Fixes #55.
=> Create search-index.json using Wattsi

src/wattsi.pas
Helps with whatwg/html#2794. Prerequisite for https://github.com/whatwg/html/pull/2816.
May also need to work on subdfn id stuff for this to really work as intended.
=> Output caniuse annotations for the dev edition as well

README.md, Syntax.md
@clelland and @yoavweiss have recently had to struggle through this, and I'd love their review or thoughts. Sorry this wasn't in place already.
=> Document the Wattsi language

README.md, src/wattsi.pas
Relates to https://github.com/whatwg/html-build/issues/177
=> Remove the bugzilla-annotations feature

src/wattsi.pas
Fixes https://github.com/whatwg/html-build/issues/203.
=> Omit MDN annotations from RDs

src/wattsi.pas
Needed for https://github.com/whatwg/html/pull/4951.
Part of https://github.com/whatwg/html-build/issues/97.
=> Support commit snapshot URLs

src/build.sh
Fixes https://github.com/whatwg/html-build/issues/157.
=> Ensure wattsi does not result in a warning on CI

README.md
Closes [issue 104](https://github.com/whatwg/wattsi/issues/104)
Thanks @annevk for helping me debug this for html-build!
=> add instructions for how to modify PATH

src/build.sh, src/html/dom.pas, src/wattsi.pas
@sideshowbarker this is an attempt at #94 with less duplicate code. However, it doesn't quite work. Let's discuss in #94.
=> [WIP] Attempt at improving MDN annotations

.github/workflows/build.yml
May help with https://github.com/whatwg/html-build/issues/211.
=> Use new Docker login action

.github/workflows/build.yml
Helps with https://github.com/whatwg/meta/issues/174.
=> Default branch rename

Syntax.md, src/wattsi.pas
Helps with https://github.com/whatwg/html/issues/5919.
=> Add w-nooutput="" support

.github/workflows/build.yml
Follows https://github.com/whatwg/html/pull/8398.
=> Meta: adopt new Ubuntu and actions/checkout

src/wattsi.pas
See https://github.com/whatwg/html/pull/8919#issuecomment-1436855187.
=> Allow data-dfn-type="dfn" plus data-export=""

src/wattsi.pas
Closes #153.
---
Who the heck knows what this means... what a wonderful language, with silent data corruption if you forget a mysterious sigil.
=> Fix long reference handling
