whatwg/wattsi

src/wattsi.pas
This is for cases where we want to emit a message pointing out a problem but
don't want to cause wattsi to end up exit non-zero just because of that problem;
e.g., problems like the w3cbugs/caniuse checking, which are not mistakes in the
spec source itself but instead can only be fixed outside the spec.
Addresses https://github.com/whatwg/wattsi/pull/6#issuecomment-165777660
=> Add Warn() function, use for w3c/caniuse ID checks

src/lib/compile.sh
When running the `MODE="RELEASE"` build, this change causes fpc to suppress
a number of different notes, hints, and warnings that we probably don't
need to be exposing to normal contributors running the build on their own.
The messages remain available when running the `MODE="DEBUG"`, etc., builds
(in which case they get processed through the `src/lib/filter.pl` script).
=> Make the MODE="RELEASE" build less noisy

src/html/htmlparser.pas, src/wattsi.pas
This change causes the exit code from wattsi to be set to `65` in the case where wattsi has reported any parse errors. For other errors, we continue to just [set the exit code to `1`](https://github.com/whatwg/wattsi/pull/6).
The special exit code for the has-parse-errors case is useful because parse errors are the only type of error for which wattsi currently emits line/column numbers—and it's useful to know if wattsi has reported any messages with line/column numbers.
And the reason it’s useful to know when wattsi has emitted messages with line/column numbers
is because in that case we want to get the correct line/column numbers from the raw source
(as opposed to the line/column numbers from pre-processed output from the raw source), which we can do by using the technique (hack) of …
=> Set specific exit code to indicate a parse error

src/wattsi.pas
This doesn't actually work, for me it warns about all the missing references and then crashes. Good enough to find the unused references, but not good enough for merging as-is.
=> Fix #16: Warn about unused references

build.sh
Without the hash-bang some systems default to "sh" shell and this is inadequate for the build scripts.
=> add hash-bang line to build.sh

src/wattsi.pas
Replace [\]^{|} with a dash (when they separate words). Drop `.
(# is removed by MungeStringToTopic already, so not needed here.)
=> Fix #22: Munge URL-forbidden characters in IDs

src/lib/compile.sh
This will avoid issues where a user tries to compile with the default Ubuntu fpc and get thrown crazy errors at them.
=> Abort compilation if fpc version isn't correct

src/wattsi.pas
I would like to use fragment-links data to normalize specification URLs. For this purpose, JSON is more suitable format than JavaScript.
Once fragment-links become a JSON, others can more easily reuse this data for their own purposes.
Please note this PR depends on a PR for whatwg/html
=> Make fragment-links true JSON

src/wattsi.pas
Fixes https://github.com/whatwg/html/issues/46.
=> Append a self-link to each heading

src/wattsi.pas
1572d7ee184601243c70e1e5994190f824de406e ended up adding links to the
TOCs of index.html and multipage/index.html though not individual
multi-page TOCs such as multipage/microdata.html. This avoids that.
A simpler fix would be to add
TElement(NewLink).RemoveChild(NewLink.lastChild);
after the while statement, but that seems less clean.
=> Avoid adding <a class=self-link> to TOCs

src/wattsi.pas
There’s only two in the HTML Standard (video element and defer/async),
but the current situation results in directly overlapping boxes that
CSS has no real way of solving.
Fixes part of https://github.com/whatwg/html/issues/2096 (I suspect we still want to use `<details>` and
adjust the styling).
=> Merge adjacent <div class=status>

src/wattsi.pas
Only do this when the `<span>` has no attributes as using the
lang/class/id attributes should continue to be okay.
Fixes #33.
=> Report lack of <dfn> for <span>s without attributes

src/wattsi.pas
Fixes whatwg/html#2225.
---
...should probably also change "5.0-5.1-10-10.1" to just "5.0-10.1", but not knowing FreePascal it's not immediately obvious to me how to do so.
=> Include last good version in caniuse boxes

src/wattsi.pas
Since % is used for escaping in URLs, having such characters in id
can be problematic. See
https://github.com/whatwg/html/pull/2558#issuecomment-295437739
---
Diff for the %ObjProto_valueOf% link in generated output:
```diff
-   [[Value]]: <a id=the-location-interface:%objproto_valueof% href=https://tc39.github.io/ecma262/#sec-object.prototype.valueof data-x-internal=%objproto_valueof%>%ObjProto_valueOf%</a>,
+   [[Value]]: <a id=the-location-interface:objproto_valueof href=https://tc39.github.io/ecma262/#sec-object.prototype.valueof data-x-internal=objproto_valueof>%ObjProto_valueOf%</a>,
```
=> Avoid % in id attributes

src/wattsi.pas
This change causes wattsi to emit a new `xrefs.json` file as part of the build.
For each `dfn` element in the spec source, the `xrefs.json` file has a list of
the spec section names that have a cross-reference to that `dfn`, and for each
section name, a list of cross-reference anchors from that section to the `dfn`.
This code should get some careful review from @Hixie
=> Generate multipage dfn cross-reference data

src/html/webdom.pas
Since HTML uses `script` at the top of `body`, omitting the start
tag causes the scripts to be inserted in `head`. Instead of writing
logic similar to SkippableTBodyStartTag, just mark 'body' as not
having an optional start tag.
=> Do not omit <body> start tag when serializing

src/wattsi.pas
Omits the small TOC, fingerprint markers, and `<pre class=idl>` blocks.
Part of #27.
=> Omit unnecessary elements in the dev edition

src/wattsi.pas
This fixes a flub that was introduced in b57d52c (though it’s not clear
it causes any observable bug).
=> Fix a code-structuring flub

src/wattsi.pas
Make the Table of Contents link to ./ instead of index.html.
Make fragment-links.json store the empty string instead of index.html.
Having index.html was bogus to begin with, because link-fixup.js would
then redirect to index.html.html.
link-fixup.js needs to be updated for this change to work correctly.
=> Avoid linking to index.html

src/wattsi.pas
There should not be any unused references; error instead of warning
catches such mistakes earlier. See https://github.com/whatwg/html/pull/2987.
=> Error instead of warning for unused reference

src/wattsi.pas
This is a partial revert of de9bac81b79ea722ede505ebf039c3e4ecb6063e.
This fixes https://github.com/whatwg/html-build/issues/121. Hopefully we
can work out something that both helps with the dev edition IDs and also
preserves IDs in the other editions, but for now, it's best to just
revert that.
This means that the dev edition will not always have IDs for the
"subdfns" included there, unless they are cross-referenced from
elsewhere. In turn, this means that the linkages to caniuse won't be
detectable in such cases.
=> Do not always ensure IDs

src/wattsi.pas
This change ensures that all subdfns in the dev edition get the right
IDs — as originally implemented in de9bac8, but this time by also
appending a `-dev` substring to the generated ID in the non-dev spec,
which ensures that in the non-dev edition, the subdfns don’t steal the
ID that the main non-subdfn definition needs to have. That prevents the
problem reported in https://github.com/whatwg/html-build/issues/121
=> Ensure subdfns get IDs (without stealing main IDs)

src/wattsi.pas
Useful for an auto-updating copyright statement.
---
This code feels suboptimal in a few ways, mainly that it duplicates the DecodeDate call with the pubdate section above it. I couldn't figure out how to deduplicate though; the scoping inside this massive function confused me too much :(. This seems good enough for now.
For the record I also tried to replace the span entirely with a new text node, but got an `EAccessViolation exception: Access violation`.
=> Add the ability to substitute in a pubyear

src/wattsi.pas
This change allows `pre` elements to have `code` children that don’t reference a `dfn` and that don’t need to to have an explicit `data-x=""` to indicate they’re not referencing a `dfn`.
Otherwise without this change, every `code` element in the source that’s a child of a `pre` needs to have `data-x=""` — because lacking that, wattsi will emit an error for it (with the message “missing `<dfn>` for topic "foo" explicitly from `<code>` element containing "bar".”).
Fixes https://github.com/whatwg/wattsi/issues/78
=> Allow <pre> to have <code> children w/o data-x=""

src/wattsi.pas
The existing wattsi code for causing IDL blocks to be omitted from the dev edition quit working when https://github.com/whatwg/html/pull/3768 moved class=idl attributes off `pre` elements and instead onto to `code` children of those elements,
So the first part of this change causes those `code class=idl` elements to be dropped as expected. But as a result of that, the now-empty `pre` element parents of those `code` elements are left behind. So the second part of this change looks for those empty `pre` elements and drops them.
Fixes https://github.com/whatwg/wattsi/issues/84
=> Ensure IDL blocks are omitted from the dev edition

README.md, src/wattsi.pas
This change causes wattsi to report an error for any instance of `<ref spec=FOO>` when no item for `FOO` is found in the References section.
Fixes https://github.com/whatwg/html-build/issues/123
=> Report an error for missing references

README.md, src/wattsi.pas
This change adds support for generating output from the `<wpt>` element, as documented at https://tabatkins.github.io/bikeshed/#wpt-element) and discussed at https://github.com/tabatkins/bikeshed/issues/1116.
Specifically, this change causes lists of tests in `<wpt>` elements from the source to generate TESTS sections in the spec output, with links to corresponding https://github.com/web-platform-tests/wpt, https://wpt.fyi and https://web-platform-tests.live URLs for the listed tests.
The change by design intentionally doesn’t provide the following `<wpt>`-related features:
- Doesn’t verify that each test listed in a `<wpt>` element actually exists in https://github.com/web-platform-tests/wpt/
- Doesn’t verify that every single test file that exists in the …
=> Add support for the <wpt> element

README.md, src/wattsi.pas
This change adds annotations in the margin of the spec output next to any items for which there’s a corresponding MDN article somewhere under https://developer.mozilla.org/en-US/docs/Web that has a Specifications section with a link to that item's URL.
The change gives wattsi a new required command-line argument for specifying the filename of a JSON file containing a mapping of spec ID-attribute values to MDN article pathnames.
Addresses https://github.com/whatwg/html-build/issues/180
=> Add MDN annotations to spec output

src/wattsi.pas
Always search for the nearest `<body>` child and insert before it.
@sideshowbarker, this removes a decent amount of the work you did, so I'm not sure I did it right. It's certainly simpler, but probably worse in various ways.
Still, it's right in the key way that if you run
```js
new Set([...document.querySelectorAll("aside.mdn")].map(el => el.parentElement.localName)).size
```
in the dev console, you get `1`, whereas on https://arcane-cove-57093.herokuapp.com/ it gives `3`.
I think we should probably merge this right away to un-break the build, but let me know if you disagree.
=> Fix and simplify MDN annotations

README.md
Note that this also intentionally removes the **Building a Wattsi binary with 64-bit code** section.
That section is an artifact of the time before fpc 3.0 was released — when we had to build fpc from the sources because Wattsi relied on features that were then as yet on only in the sources targeted for release in fpc 3.0 but not actually released yet.
But the guidance in the readme is now strictly about installing pre-built fpc binaries — we no longer provide any other guidance on building from the sources — so there’s no reason to keep that **Building a Wattsi binary with 64-bit code** section around any longer.
=> Add more fpc install guidance to README.md

src/build.sh, src/wattsi.pas
This change causes all MDN annotations in the spec to be collapsed by default. To view the contents of an annotation, users need to click on the MDN marker widget to expand the contents.
This aligns with the behavior of specs published using Respec, and on balance seems like better user experience in general. It comes with the downside of making the annotation contents less discoverable to new readers of the spec — but the tradeoff is that it prevents the cases where the spec contents are obscured by annotations (for long interface names and such), and overall makes the spec pages less cluttered and more readable.
Fixes https://github.com/whatwg/html/issues/4635
Relates to https://github.com/whatwg/html/issues/4236
=> Collapse MDN annotations by default

src/wattsi.pas
See https://github.com/whatwg/whatwg.org/pull/64
=> Update URL to fingerprint image

src/build.sh, src/wattsi.pas
This change causes wattsi to stop if it receives an HTTP response from the highlighter with a 400 status code.
Relates to https://github.com/whatwg/html-build/issues/201 (“Build does not fail on invalid Web IDL”)
---
This doesn’t work yet in practice for what we actually need it for, which is to make the build fail for invalid Web IDL, as reported in https://github.com/whatwg/html-build/issues/201.
The reason it doesn’t work in practice is that, as far I can tell, the highlighter doesn’t actually respond with a 400 when it encounters a Web IDL syntax error. See https://github.com/tabatkins/highlighter/issues/14.
=> Fail if the highlighter responds with 400 status

src/build.sh, src/wattsi.pas
This change causes Wattsi to nil(null)-check the "support" object from the imported mdn-spec-links JSON data before trying to perform any operations with the object.
Without this change, if the "support" object’s value is null in the imported mdn-spec-links JSON data, wattsi crashes.
---
This change un-breaks the HTML spec build. (I had broken it with some changes I made to how the https://raw.githubusercontent.com/w3c/mdn-spec-links/master/html.json file gets generated.)
=> Add nil check for mdn-spec-links JSON support data

src/build.sh, src/wattsi.pas
This change updates the support/compat sections of the MDN annotations to add an "Edge (Legacy)" row, in addition to the existing "Edge" row (which now shows data for current Blink-based Edge).
=> MDN annos: Split out "Edge (Legacy)" from Edge

src/build.sh, src/wattsi.pas
In the MDN annotations, this change adds an indicator symbol within the version-number column in any cell for a browser whose implementation of the associated feature isn’t exposed by default but instead requires setting a user preference or runtime flag.
This change also rewrites the underlying algorithm for determining from the BCD data whether a particular browser supports a given feature — to fix a fundamental problem in the existing code which causes it to, in some cases, wrongly add multiple rows for some browsers to the support tables in the MDN annotations, with different version numbers and different/ conflicting indications of whether the browser supports the feature.
=> MDN annos: Mark flag-needed features w/ indicator; fix underlying algorithm

src/build.sh, src/wattsi.pas
This change adds indicator symbols and text in the MDN annotations, to give information about the number of browser engines which support the feature associated with the annotation.
=> MDN annos: Show less-than-2/all-engines indicators

src/build.sh, src/wattsi.pas
This PR is an alternative to #112 that just solves the same single *“Ensure MDN annos for headings go into right split”* problem we originally set out to solve in #94 and #95 — but without trying to solve the separate *“avoid having annos end up overlapping with paragraph text”* issue.
The *“avoid having annos end up overlapping with paragraph text”* issue is no longer a problem in practice, because we now minimize the annos by default — so the annos don’t overlap unless expanded, and then users can just unexpand/re-minimize them to view any text they overlap.
This branch has two commits:
* fb3b0dd, which is a revert of the 2deef18 commit we merged to master from #95 
* d441d64, which is a slightly-modified version of 68e817e (the part of #94 that addressed just the *“Ensure MDN annos for …
=> Ensure MDN annos for headings go into right split (revisited)

src/wattsi.pas
This change aligns the Wattsi-generated MDN-anno markup and classnames with those that Bikeshed outputs. That allows us to use the same styles in https://resources.whatwg.org/standard-shared-with-dev.css for both all WHATWG Bikeshed-generated standards and for the HTML standard. So this depends on whatwg/whatwg.org#311.
*“Reorder browser lists into groups”* 8151408 is an additional commit in this branch, to cause the browser ordering in MDN annos to match the same ordering that Bikeshed outputs.
The branch in this PR also includes two other commits with MDN-anno refinements:
* Show removed-feature version ranges 8700d45
* Handle nonconforming support cases 20cf86b
…so this PR may be easier to review if the commits in this branch are reviewed individually (rather than reviewing the diff …
=> MDN annos: Align with Bikeshed-generated markup and styles; other refinements

src/build.sh, src/html/dom.pas, src/wattsi.pas
This change ensures that for elements we’re annotating which are inside tables or lists, each anno ends up placed as expected in horizontal alignment with the element it’s annotating.
Otherwise, without this change, in cases where we have a long table (e.g., the list of events in the index) or long `<dl>` list (e.g., the list of pseudo-classes), all the annos for everything in that table or list end up being merged into a single annotation way up at the beginning of the table or list — which prevents them from being discoverable to readers.
Depends on https://github.com/whatwg/whatwg.org/pull/314
---
https://html-mdn.herokuapp.com/output/ has the output from this; see in particular:
* https://html-mdn.herokuapp.com/output/multipage/semantics-other.html#pseudo-classes
* …
=> MDN annos: Fix placement of annos in tables/lists

.editorconfig, .gitignore, .travis.yml, Dockerfile, Makefile, README.md, build.sh, src/build.sh, src/lib/compile.sh
This adds a Dockerfile which, when built, contains the Wattsi executable (with debian:stable-slim as the base). This effectively provides pre-built Wattsi binaries, uploaded to the Docker hub, for those with Docker available. It also gives us CI coverage for Wattsi, which we were lacking.
This closes #192 by removing the hard-coded version. With this in place the HTML build infrastructure should no longer need that.
Along the way, this adds shebangs to various .sh files (required in at least some OSes, including the Debian one we're using in Docker), and removes the test commands from the compile.sh script (those can be run separately, after building).
---
I think this is mergeable now, although it might mess up some of the version number stuff. I'll work on a corresponding html-build PR …
=> Build and deploy Wattsi on CI using Docker

Dockerfile
This reduces the (uncompressed) size of the resulting Docker image from 99.3 MiB to 25.4 MiB, by starting a fresh image and only copying over the built result. A good chunk of this reduction comes from using the "distroless" base image for the final result (gcr.io/distroless/base).
By splitting the RUN commands, it also reduces iteration time: if the contents of /whatwg/wattsi/src change, running `make docker` will no longer require reinstalling all of the build dependencies inside the container, and instead the cached image with those dependencies will be reused, with only the steps from the COPY command onward re-done. (Splitting the RUN commands in this way was avoided previously because it would increase the size of the image, but with multi-stage builds, this is not a problem. See …
=> Use multi-stage builds in the Dockerfile

Makefile
I forgot to update the manual target when I made version.inc mandatory.
Additionally, it's nicer to have the default for "make" be the manual target, instead of clean.
=> Fix the Makefile for manual builds

src/wattsi.pas
This change adds a new command-line option to cause wattsi to skip generating all output variants other than the single-page version.
=> Add an option to only generate single-page output

README.md, src/wattsi.pas
This change removes the code for generating caniuse.com annotations.
Relates to https://github.com/whatwg/html-build/issues/213
We shouldn’t merge this until after we’re done reviewing the output at https://github.com/whatwg/html-build/issues/213#issuecomment-643076510
=> Stop generating canuise.com annotations

.github/workflows/build.yml
https://github.com/whatwg/html-build/blob/51f79655b59f3872a75ed827439cd4a3de2d98fd/build.sh#L603
It does the same thing right now, but just as well to be consistent.
=> Get Wattsi version in the same way as html-build

src/wattsi.pas
This change adds caniuse.com links to all MDN annotations for which there’s a corresponding page at caniuse.com.
Depends on https://github.com/whatwg/whatwg.org/pull/324.
Relates to https://github.com/whatwg/html-build/issues/213
https://html-mdn.herokuapp.com/output/ can be used to preview the rendered output this change produces.
=> MDN annos: Add caniuse.com links

src/wattsi.pas
This change causes the handling of MDN annotations for descendants of headings to match the existing handling we’re already using for headings themselves (landed in dab062c). Specifically, if an element is a descendant of a heading, any MDN annotation generated for that element is inserted after the heading element in the DOM (rather than before).
Otherwise, without this change, if an element is a descendant of a heading and we insert an MDN annotation for that element, the annotation is inserted before the heading — which causes the same problem described in the dab062c commit message (in multipage output, the annotation can end up orphaned in the previous split; and in both multipage and single-page output, the annotation isn’t aligned with the heading). …
=> Fix handling of MDN annos for heading descendants

src/wattsi.pas
This change makes Wattsi emit `<div>` elements for MDN annos, rather than `<aside>` elements.
Otherwise, without this change, some markup that Wattsi emits for MDN annos doesn’t conform to current HTML spec requirements. Specifically, the HTML spec currently doesn’t allow `<aside>` elements as descendants of `<dt>` elements — but we are intentionally inserting MDN annos as `<dt>` descendants (to get them aligned at point of use). So because of that, for now at least we need to use `<div>` for the annos, rather than `<aside>`.
Relates to https://github.com/whatwg/wattsi/issues/129
=> MDN annos: Use <div> rather than <aside>

src/html/dom.pas, src/lib/compile.sh, src/lib/ropes.pas, src/wattsi.pas
fpc 3.2.0 is apparently stricter about a few things, and our existing code has a couple of cases that cause fatal errors when compiling with fpc 3.2.0 — as well as a lot of cases that cause an informational message to get emitted that prevoius fpc versions did not emit for our code.
So in this PR branch, there are multiple commits:
1. A change that replaces the `Document.DocType` and `Document.DocumentElement` properties with `Document.GetDocType()` and `Document.GetDocumentElement()` methods in the `src/html/dom.pas` source, and updates the `src/wattsi.pas` application code to use the `Document.GetDocumentElement()` method. (The `Document.DocType` property was not actually used in the existing code.)
Otherwise, without that change, fpc fails with these fatal errors:
> dom.pas(120,55) …
=> Updates to compile successfully with fpc 3.2.0

src/wattsi.pas
This change drops an error that Wattsi otherwise emits for the case where a heading has an empty `span` or `dfn` (that is, with no text content), followed by another `span` or `dfn` in the same heading.
The current code appears to have been (for some reason that’s not obvious now) very intentionally written to report an error for exactly that case — but not for the case where of a heading with *non-empty* `span` or `dfn` followed by another `span` or `dfn` in the same heading.
Without this change, Wattsi reports an error for a reasonable markup case like the one in https://github.com/whatwg/html/pull/5855; that is, this:
```html
<h5 id="rel-alternate"><span id="link-type-alternate"></span>Link type "<dfn data-export=""
data-dfn-for="link/rel,a/rel,area/rel" …
```
=> Drop the “nested dfn or span in heading” error

src/wattsi.pas
This change adds support for doing the following with attributes of `dfn` elements:
* recognize attributes with names that are known dfn types (currently: `element`, `element-attr`, `event`, `interface`, `extended-attribute`, `method`, `attribute`, `enum-value`, and `http-header`), and replace them with corresponding `data-dfn-type=element`, etc., attributes in output
* for any `dfn` element that has an attribute named `for`, replace it in output with an attribute named `data-dfn-for`
* for any `dfn` element with an `export` or `noexport` attribute , replace it with one named `data-export` or `data-noexport`
Relates to https://github.com/whatwg/html/pull/5694/
---
This patch does what I’ve inferred the desired behavior is, based on what I understand from the …
=> Support dfn types short syntax, "for", (no)export

src/wattsi.pas
This reverts commit 7e4d1e8f42b6d9f6a4a355c0213aa91b4f47605d
temporarily, as it breaks building the HTML Standard on master. When
https://github.com/whatwg/html/pull/5916 is finished and merged, then we
can add this check back.
=> Revert "Fail with an error if export used w/ dfn type"

src/wattsi.pas
This change makes Wattsi handle the translation of Bikeshed short syntax in heading elements.
Otherwise, without this change, Wattsi only handles the translation for dfn elements (and because the HTML source has instances of the short syntax on heading elements, those failed to get translated).
=> Handle dfn types short syntax, etc., in headings

README.md
Running the previous version gave this message:
```
Bash. Please migrate to the following command:
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
```
=> Update Homebrew installation command to use Bash

src/build.sh
I don't know how often people run into this, but I found this to be necessary to build `wattsi` on one of my macOS Big Sur systems.
=> Fix wattsi compilation on macOS Big Sur.

Syntax.md
Within the context of this section's example `<dfn>`, it contradicted the point made a couple lines earlier that Wattsi does not do pluralization.
=> Fix case-insensitivity example

.github/workflows/build.yml, Makefile
Docker Hub was planning to sunset their free plan: https://www.docker.com/developers/free-team-faq/. Although they have backed down from doing this, it still seems better to centralize our infrastructure dependencies on GitHub.
---
We'll see if this works as expected... probably a few force-pushes in this repo's future.
=> Move to GitHub Container Registry

Syntax.md, src/html/htmlparser.pas, src/wattsi.pas
Instead of a nonstandard void element `<ref spec=FOO>`, use the text content: `<ref>FOO</ref>`.
This allows us to use standard HTML parser/serializer tooling with the HTML source, e.g. for https://github.com/whatwg/html-build/pull/279.
---
This needs to be merged in close concert with corresponding html-build and html PRs.
Note that some trailing whitespace removal seems to have showed up in `htmlparser.pas`. Oh well?
=> Change <ref> syntax

src/lib/ropes.pas
Something like what’s in the patch in this PR would’ve prevented the problem introduced in https://github.com/whatwg/wattsi/pull/152 and reported in https://github.com/whatwg/wattsi/issues/153.
The problem is: the `Append()` method for Ropes allows passing in either a string or a pointer to a string. And in the case where a string is passed in, the runtime silently truncates the string if it exceeds a certain length (`UTF8InlineSize`, which in practice seems to be 15). But when instead a pointer to a string is passed in, it doesn’t matter how long the string is.
The intent of allowing strings to be passed to `Append()` seems to have been just for very short string _constants_. So we really shouldn’t use  `Append()` with strings other than constants; we should instead always pass in …
=> Fail if Append()ing string to Rope in excess of TInlineString size

src/wattsi.pas
The string/rope semantics continue to bite us. The original fix in bd1cd4460609a8284bb92fd4a4c407f4cc7b68fb was not correct, for unclear reasons. This version uses ExtractAll() to ensure we get a fresh CutRope that we can AppendDestructively() to Scratch, which is more in line with what other parts of the file do.
=> Fix the <ref> processing again

.github/workflows/build.yml
Per the Docker documentation [1], setup a github actions workflow to create both an amd64 and an arm64 image.
This can be tested locally like so:
- Create a docker-container builder that will use qemu-static-user
`docker buildx create --name container --driver=docker-container --use`
- Run the build using docker buildx with that new 'builder'
```
docker buildx build --builder=container \
--platform linux/amd64,linux/arm64 .
```
Also update the actions to their latest revs.
[1] https://docs.docker.com/build/ci/github-actions/multi-platform/
=> CI: Create a multiplatform docker image using docker buildx features

src/wattsi.pas
Since https://github.com/whatwg/whatwg.org/pull/444 *tracking-vector.svg* is now darkmode-aware, i.e. its fill color will be dependent on the user's darkmode settings. However from https://github.com/whatwg/whatwg.org/pull/439 `<img>` tags pointing at svg images that don't have a `"darkmode-aware"` class are given a white background by default. This makes the tracking-vector image fully white when seen in dark-mode. This PR aims at fixing it by adding the class on the generated `<img>` element.
Note that I'm not entirely sure this is the only source for this image in all the specs, but I tested it with html-build where it already handles a bunch.
Before:
After:
=> Fix tracking-vector image in dark-mode

src/wattsi.pas
**Resolves**:
* https://github.com/whatwg/wattsi/issues/162
* https://github.com/whatwg/wattsi/issues/163
* https://github.com/whatwg/wattsi/issues/77
**Before**:
```sh
$ ./bin/wattsi
wattsi: output directory (second argument) must be an existing empty directory
$ echo $?
0
```
**After**:
```sh
$ ./bin/wattsi
wattsi: missing required arguments
syntax:
wattsi [--quiet] [--single-page-only] <source-file> <source-git-sha> <output-directory> <default-or-review> <mdn-spec-links/html.json> [<highlight-server-url>]
wattsi --version
$ echo $?
1
```
=> Print usage if args not provided
